<ips:template parameters="" />

<div class="ipsBox ipsPad ipsSpacer_top" id="rpsBox">
	<div class="ipsType_richText ipsStyle_center ipsType_break ipsContained">
		<!--<h1>Roshambo</h1>-->
		<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Rock-paper-scissors.svg/460px-Rock-paper-scissors.svg.png">
		<br> <br>
		<a class="ipsButton ipsButton_normal" href="{url='app=rps&module=rps&controller=play&do=play'}">Let's Play!</a>
	</div>
</div>