<ips:template parameters="" />
<div id="ipsLayout_contentWrapper">
	<div class="ipsStyle_center" id="ipsLayout_mainArea">
		<h1>Choose Your Move!</h1>
		<br> <br>
		<a class="ipsButton ipsButton_primary"><i class="fa fa-hand-rock-o"></i> &nbsp;Rock</a>
		<a class="ipsButton ipsButton_primary"><i class="fa fa-hand-paper-o"></i> &nbsp;Paper</a>
		<a class="ipsButton ipsButton_primary"><i class="fa fa-hand-scissors-o"></i> &nbsp;Scissors</a>
	</div>
	<div id="ipsLayout_sidebar" class="ipsLayout_sidebarright">
		<aside id="elContextualTools" class="ipsClearfix">
			<div id="elRpsScoreboard" class="ipsWidget ipsWidget_vertical ipsBox">
				<h3 class="ipsType_sectionTitle ipsType_reset">Scoreboard</h3>
				<div class="ipsPad_half">
					<div class="ipsSideMenu">
						<ul class="ipsSideMenu_list">
							<li>
								<span class="ipsBadge ipsBadge_style1 ipsPos_right" id="rpsComputerScore">1</span>
								<strong class="ipsType_normal"><i class="fa fa-desktop"></i> &nbsp;Computer</strong>
							</li>

							<li>
								<span class="ipsBadge ipsBadge_style1 ipsPos_right" id="rpsPlayerScore">1</span>
								<strong class="ipsType_normal"><i class="fa fa-user"></i> &nbsp;{member="name"}</strong>
							</li>

							<li>
								<span class="ipsBadge ipsBadge_style1 ipsPos_right" id="rpsPlayerScore">1</span>
								<strong class="ipsType_normal"><i class="fa fa-exchange"></i> &nbsp;Draws</strong>
							</li>
						</ul>

						<p class="ipsType_center">
							<a href="{url='app=rps&module=rps&controller=play&do=resetScore'}" class=""><i class="fa fa-refresh"></i> &nbsp;Reset Score</a>
						</p>
					</div>
				</div>
			</div>
		</aside>
	</div>
</div>