<ips:template parameters="" />

<div id="ipsLayout_contentWrapper">
	<div id="ipsLayout_mainArea">
		<!--<h1>Roshambo</h1>-->
		<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Rock-paper-scissors.svg/460px-Rock-paper-scissors.svg.png">
		<br> <br>
	</div>
	<div id="ipsLayout_sidebar" class="ipsLayout_sidebarright " data-controller="core.front.widgets.sidebar">

		<aside id="elContextualTools" class="ipsClearfix">



			<div id="elDownloadsCategories" class="ipsWidget ipsWidget_vertical ipsBox">
				<h3 class="ipsType_sectionTitle ipsType_reset">Categories</h3>
				<div class="ipsPad_half">
					<div class="ipsSideMenu">
						<ul class="ipsSideMenu_list">


							<li>
								<a href="http://ipb.dev/?app=downloads&amp;module=downloads&amp;controller=browse&amp;id=1" class="ipsSideMenu_item  ipsTruncate ipsTruncate_line"><span class="ipsBadge ipsBadge_style1 ipsPos_right cDownloadsCategoryCount">1</span><strong class="ipsType_normal">Files</strong></a>

							</li>


						</ul>
						<p class="ipsType_center">
							<a href="http://ipb.dev/?app=downloads&amp;module=downloads&amp;controller=browse&amp;do=categories" class="">Browse Categories &nbsp;<i class="fa fa-caret-right"></i></a>
						</p>
					</div>

				</div>
			</div>
		</aside>





		<div class="cWidgetContainer ipsHide" data-controller="core.front.widgets.area" data-role="widgetReceiver" data-orientation="vertical" data-widgetarea="sidebar">
			<ul class="ipsList_reset">

			</ul>
		</div>

	</div>
</div>